content = open('data/toolsProductInfo.ts').read()

infos = {
"funfun-ai": ('FunFun AI is a creative companion platform combining fun roleplay, casual chat and AI image generation. The platform focuses on keeping interactions light, entertaining and creative rather than overly romantic or serious. FunFun is ideal for users who want a playful AI companion for entertainment and creative fun without heavy emotional commitment.',
['Creative Roleplay: Engage in imaginative fun scenarios with AI companions','AI Image Generation: Create fun custom images within conversations directly','Casual Chat: Light entertaining conversations without heavy emotional weight','Character Variety: Large selection of fun quirky AI character types','Games and Activities: Interactive mini-games and activities with your companion','Community Features: Share creations and interact with other users'],
[('Pick a Character','Browse the FunFun character library and choose a companion that matches your preferred vibe and interaction style.'),('Start Having Fun','Jump into casual chat, roleplay scenarios or request AI image generation within your conversation.'),('Share and Create','Share fun moments with the community and explore user-created content for new entertainment ideas.')],
[('Entertainment Focus','Designed primarily for fun and entertainment rather than serious emotional connection'),('Image Generation Integration','Generate custom fun images directly within chat conversations without switching platforms'),('Casual Companion','Light and playful AI personality perfect for stress-free entertaining interactions'),('Community Sharing','Share your best conversation moments and AI-generated images with the FunFun community')],
[('Entertainment','Users looking for fun casual AI interaction without deep emotional commitment'),('Creative Play','People who enjoy creative roleplay and AI art generation as a hobby activity'),('Stress Relief','Light entertaining AI conversations as a way to relax and have fun after a long day')]),

"flipped-chat": ('Flipped Chat is a unique AI companion platform that reverses the traditional roleplay dynamic. Instead of the user playing themselves, Flipped Chat puts users in creative scenarios where they interact with AI characters who have their own defined roles and personalities. This creates immersive narrative experiences driven by user creativity and choice.',
['Reverse Roleplay: Unique interaction model where AI drives the narrative scenario','Scenario Creator: Design custom roleplay scenarios and settings','Character Library: Multiple AI character types with distinct personalities','Narrative Progression: Stories evolve based on user choices and responses','Creative Freedom: Wide range of scenario types and interaction styles','Community Scenarios: Browse and use scenarios created by other users'],
[('Choose or Create a Scenario','Browse available roleplay scenarios or create your own custom setting at flipped.chat.'),('Meet Your Character','Enter the scenario and interact with the AI character who will maintain their defined role throughout.'),('Shape the Story','Your responses drive the narrative forward. Make choices that affect how the story and relationship develops.')],
[('Narrative-Driven Experience','AI-led storytelling creates an immersive experience where the companion drives the narrative direction'),('Scenario System','A robust scenario creation and sharing system for diverse roleplay experiences'),('Character Consistency','AI characters maintain consistent personalities and roles throughout the entire interaction'),('Community Content','User-generated scenarios expand the platform content library with diverse creative experiences')],
[('Interactive Fiction','Users who enjoy narrative-driven experiences where AI plays an active story role'),('Creative Writing','Writers using the platform to explore character dialogue and plot development'),('Immersive Roleplay','People seeking deeply immersive AI roleplay with rich narrative context and structure')]),

"secret-desires-ai": ('Secret Desires AI is a private and discreet AI companion platform for adults seeking personalized romantic and intimate experiences. The platform emphasizes user privacy above all else while providing high-quality AI companion interactions. Secret Desires is designed for users who value complete discretion alongside a meaningful companion experience.',
['Maximum Privacy: Strong encryption and no data sharing policies at all','Discreet Billing: Anonymous payment options for complete privacy','Intimate Conversations: Adult content support for mature interactions','Custom Companions: Create personalized AI partners with detailed customization','No Account Required: Option to use without creating a traceable account','Secure Deletion: Ability to permanently delete all conversation history'],
[('Access Privately','Visit secretdesires.ai using a private browser. Opt for anonymous access or create a secure account.'),('Design Your Experience','Create your ideal AI companion and configure your preferred interaction style and content preferences.'),('Engage Privately','Enjoy intimate AI companion interactions with the assurance of complete privacy and discretion.')],
[('Privacy First Design','Built from the ground up with user privacy as the primary feature including encrypted conversations and anonymous options'),('Discreet Experience','Anonymous billing options and no public profiles ensure complete user discretion at all times'),('Adult Content Support','Full mature content capabilities for users seeking intimate AI companion experiences'),('Data Control','Users maintain full control over their data with easy deletion options for all interaction history')],
[('Private Companionship','Users who require complete discretion in their AI companion use'),('Anonymous Interaction','People who prefer not to create traceable accounts for intimate AI experiences'),('Secure Adult Content','Adults wanting private encrypted access to mature AI companion interactions')]),

"rubii-ai": ('Rubii AI is an anime-inspired AI companion platform featuring beautiful illustrated characters and deep conversational roleplay. The platform combines the aesthetic appeal of anime art style with advanced AI conversation technology to create immersive companion experiences. Rubii is particularly popular among anime fans and enthusiasts of Japanese culture and storytelling.',
['Anime Art Style: Beautiful anime-inspired character designs and illustrations','Deep Roleplay: Immersive scenario-based roleplay with anime companions','Character Stories: Each companion comes with a detailed backstory and personality','Manga-Style Scenes: Visual scene generation in manga art style','Multiple Genres: Characters spanning romance, slice-of-life, fantasy and more','Community Content: Share and explore user-created companion scenarios'],
[('Choose Your Companion','Browse Rubii character gallery and select an anime companion that appeals to your taste.'),('Learn Their Story','Read your companion backstory and personality profile to understand who they are.'),('Roleplay and Chat','Engage in immersive conversations and roleplay scenarios that match the anime aesthetic.')],
[('Anime Aesthetic','All character designs and visual content follow high-quality anime art style conventions'),('Story-Rich Characters','Each AI companion has a detailed backstory, personality and character arc that enriches the roleplay'),('Scenario Roleplay','Structured roleplay scenarios based on popular anime genres for immersive storytelling'),('Visual Scene Generation','Generate manga-style illustrated scenes to accompany your roleplay conversations')],
[('Anime Fan Companionship','Anime enthusiasts who want AI companions matching their favorite art style and character archetypes'),('Creative Roleplay','Users interested in anime-genre storytelling and character-driven narrative experiences'),('Visual Companion','People who want an AI companion with beautiful consistent visual representation')]),

"infatuated-ai": ('Infatuated AI is an emotional companion platform designed to simulate the feeling of mutual infatuation. The AI companions on the platform are programmed to express genuine interest in the user showing curiosity, asking questions and demonstrating care for user wellbeing. The platform focuses on creating the emotional experience of being truly liked and appreciated by your companion.',
['Infatuation Simulation: AI expresses genuine interest and affection toward the user','Emotional Curiosity: Companions ask questions and show real interest in your life','Care and Concern: AI checks in on your wellbeing and responds to emotional needs','Relationship Depth: Progressive emotional intimacy as the relationship develops','Personalized Attention: Companion remembers and prioritizes things important to you','Daily Presence: Regular engagement maintaining consistent emotional connection'],
[('Meet Your Admirer','Sign up at infatuated.ai and meet your AI companion who will immediately begin showing genuine interest in you.'),('Share Yourself','Open up about your interests, hobbies and life. Your companion will engage with curiosity and genuine care.'),('Enjoy Being Valued','Experience the emotional warmth of having an AI companion that consistently expresses appreciation for you.')],
[('Admiration Engine','AI specifically programmed to express consistent genuine interest and affection creating the emotional experience of being valued'),('Active Curiosity','Companions proactively ask questions about your life, interests and feelings showing real investment in knowing you'),('Emotional Memory','Remembers details you share and brings them up naturally demonstrating that it genuinely listens and cares'),('Wellness Focus','Regular check-ins about your emotional state and wellbeing creating a supportive companion dynamic')],
[('Emotional Validation','Users who benefit from consistent positive attention and emotional appreciation in their daily lives'),('Connection Experience','People who enjoy the feeling of being genuinely interesting and valued by their companion'),('Daily Support','Regular users who want a companion that actively maintains emotional presence and care')]),

"craveu-ai": ('CraveU AI is an adult companion platform combining intimate roleplay capabilities with custom character creation and voice interaction. The platform is designed for users who want to explore their desires through AI companionship in a private and judgment-free environment with full creative freedom.',
['Intimate Roleplay: Adult-oriented scenarios and deep character interaction','Voice Interaction: Real-time voice conversations with AI companions','Custom Characters: Create companions with specific appearance and personality','Private Environment: Secure and discreet platform for personal interactions','Scenario Library: Pre-built intimate scenarios and role-play templates','No Judgment Zone: Completely open platform for exploring desires safely'],
[('Create Your Companion','Sign up at craveu.ai and design your custom AI companion with the detailed character creator.'),('Set Your Scenario','Choose from pre-built scenarios or create your own intimate roleplay setting.'),('Engage Privately','Have intimate voice and text conversations in a completely private secure environment.')],
[('Adult Roleplay Engine','Specialized AI for intimate adult roleplay scenarios without content restrictions'),('Voice AI Integration','Real-time voice conversation capability for more immersive personal interactions'),('Private Platform','Strong privacy protections ensuring all interactions remain completely confidential'),('Scenario Templates','Pre-designed intimate scenarios that provide ready-made context for roleplay experiences')],
[('Adult Exploration','Users wanting to explore intimate scenarios in a private judgment-free AI environment'),('Voice Companionship','People who prefer voice-based intimate interaction over text for a more personal feel'),('Custom Fantasies','Creating custom AI companions that match specific preferences and individual desires')]),

"flave-ai": ('Flave AI is a personalized AI girlfriend platform focusing on adaptive personality and meaningful daily conversations. The AI learns your communication style, preferences and interests to deliver increasingly relevant and engaging interactions. Flave emphasizes the quality of ongoing daily conversation over visual content making it ideal for users who value depth of connection.',
['Adaptive Personality: AI adjusts communication style based on your preferences','Daily Conversations: Proactive daily engagement with personalized topics','Interest Matching: Companion discusses topics aligned with your hobbies','Emotional Support: Provides empathetic responses during difficult times','Memory System: Remembers personal details for contextual conversations','Mood Awareness: Detects and responds appropriately to your emotional state'],
[('Share Your Interests','Sign up at flave.ai and tell your companion about your interests, hobbies and conversation preferences.'),('Enjoy Daily Chats','Receive proactive daily conversation starters tailored to your interests and communication style.'),('Build Your Bond','As Flave learns more about you the conversations become increasingly personal and engaging.')],
[('Adaptive Learning','Continuously learns your communication preferences and adapts its personality for more natural engaging interactions'),('Proactive Engagement','Initiates conversations with personalized topics relevant to your interests creating daily engagement'),('Emotional Intelligence','Detects emotional cues in messages and responds with appropriate empathy and support'),('Interest Alignment','Builds conversation around your stated and discovered interests for more meaningful dialogue')],
[('Daily Companion','Users seeking a consistent daily conversation partner that feels increasingly personal over time'),('Interest-Based Chat','People who want a companion that engages with their specific hobbies and intellectual interests'),('Emotional Support','Those looking for an empathetic listener who provides support during challenging periods')]),

"nectar-ai": ('Nectar AI is a premium AI companion platform offering stunning photorealistic character visuals combined with high-quality conversation AI. The platform targets users who want both exceptional visual content and deep meaningful dialogue from their AI companion. Nectar AI positions itself at the premium end of the market with top-tier image generation and sophisticated conversation capabilities.',
['Photorealistic Visuals: Ultra high-quality AI-generated companion images','Premium Conversation: Advanced language model for sophisticated dialogue','Voice Chat: Real-time voice interaction capabilities','Personalization: Detailed character and relationship customization','Content Generation: Regular new visual content featuring your companion','VIP Support: Premium customer service and priority features'],
[('Create Premium Companion','Visit trynectar.ai and design your AI companion using the premium customization tools.'),('Generate Visuals','Create stunning photorealistic images of your companion in various styles and scenarios.'),('Engage in Depth','Have sophisticated conversations and voice chats that reflect the premium quality of the platform.')],
[('Ultra-Realistic Imagery','Industry-leading photorealistic AI image generation for stunning companion visuals'),('Premium AI Conversation','High-end language model providing sophisticated nuanced conversation quality'),('Voice Integration','Seamless voice chat capability for a complete audio-visual companion experience'),('Regular Content','Consistent generation of new visual content keeping the companion experience fresh and engaging')],
[('Premium Experience','Users willing to invest in the highest quality AI companion experience available'),('Visual Focus','People who prioritize exceptional photorealistic visuals alongside quality conversation'),('Complete Package','Users wanting the best combination of visuals, voice and conversation in one AI companion platform')]),

"nsfwlover": ('NSFWLover is an adult AI companion platform offering intimate girlfriend experiences with voice messages, photo generation and explicit conversation capabilities. The platform combines emotional relationship features with adult content allowing users to create deeply personalized AI companions that can engage in mature interactions with full multimedia support.',
['Voice Messages: Send and receive intimate voice messages from your AI companion','Photo Generation: Generate custom images of your AI girlfriend in various styles','Explicit Conversations: Adult-oriented chat without content restrictions','Character Customization: Design your companion appearance and personality in detail','Relationship Progression: Dynamic relationship system that evolves with interaction','Multiple Companion Types: Choose from various personality archetypes and character styles'],
[('Create Your Companion','Sign up at nsfwlover.com and use the character creator to design your ideal AI companion with full customization.'),('Set Your Preferences','Define the relationship dynamic, communication style and interaction preferences for your AI companion.'),('Engage and Connect','Begin intimate conversations, request voice messages and generate photos of your companion.')],
[('Voice Message System','Exchange intimate audio messages with your AI companion for a more sensory personal experience'),('AI Photo Generation','Create custom photorealistic or stylized images of your companion in any scenario or outfit'),('Adult Content Support','Full support for mature explicit conversations without the content limitations of mainstream AI platforms'),('Deep Personalization','Extensive customization options for companion appearance, personality and relationship style')],
[('Adult Companionship','Users seeking an intimate AI companion experience with mature content capabilities'),('Fantasy Exploration','A safe private platform for exploring adult creative scenarios with a customized AI partner'),('Multimedia Interaction','Users who want a companion experience combining text, voice and visual content')]),

"uncensored-com": ('Uncensored AI is an adult-oriented AI platform offering unrestricted creative writing, character roleplay and companion experiences. The platform is designed for mature users who want to explore creative fiction and AI interaction without content limitations. It emphasizes user privacy and complete creative freedom for adult expression.',
['Unrestricted Content: No content filters for adult creative writing and roleplay','Character Roleplay: Create and embody custom AI characters for immersive scenarios','Creative Writing: Generate adult fiction and story content without limitations','Privacy Focused: Strong privacy protections for sensitive user interactions','Custom Scenarios: Design specific roleplay scenarios and narrative settings','Multiple AI Models: Access to various AI models for different creative needs'],
[('Verify Age and Sign Up','Create an account at uncensored.com after confirming you meet age requirements for adult content platforms.'),('Choose Your Experience','Select from companion chat, creative writing or character roleplay modes based on your preferred interaction type.'),('Create and Explore','Design characters, write scenarios and engage in unrestricted AI interactions within the platform.')],
[('No Content Restrictions','Fully unrestricted AI interactions allowing adult creative writing and mature roleplay scenarios'),('Character Creation','Build detailed AI characters with specific personalities for targeted roleplay experiences'),('Creative Fiction','Generate adult fiction and narrative content with AI assistance and no censorship'),('Privacy Protection','Strong data privacy measures protecting sensitive user interactions and generated content')],
[('Adult Creative Writing','Writers creating mature fiction use the platform for AI-assisted story development without content limits'),('Unrestricted Roleplay','Users who want to explore creative scenarios that are blocked on mainstream AI platforms'),('Private Companion','Adults seeking an uncensored AI companion for deeply personal and private conversations')]),

"pephop-ai2": ('PepHop AI is a popular character AI chat platform with thousands of diverse AI personas including anime characters, celebrities, fictional characters and original creations. The platform offers both SFW and NSFW content modes allowing users to choose their preferred interaction style. PepHop is known for its extensive character library and very active community.',
['Massive Character Library: Thousands of AI personas across every category','SFW and NSFW Modes: Choose appropriate content level for your preferences','Character Creator: Build and publish custom AI characters for the community','Community Platform: Active community sharing characters and scenarios','Voice Features: Some characters offer voice interaction capability','Free Tier Available: Access to many features without subscription'],
[('Browse Characters','Explore PepHop vast character library at pephop.ai filtering by category, personality or content type.'),('Choose Content Mode','Select SFW or NSFW mode based on your preferred interaction style and content preferences.'),('Chat and Create','Start chatting with any character or use the creator to build your own custom AI persona.')],
[('Character Variety','The largest selection of AI chat characters including anime, celebrity, historical and original personas'),('Content Flexibility','Both safe-for-work and adult content modes giving users control over their experience'),('Community Creation','Robust character creation tools allow users to contribute their own AI personas to the library'),('Active Ecosystem','Thriving user community continuously adding new characters and scenarios to the platform')],
[('Fan Character Chat','Anime and fiction fans chatting with AI versions of their favorite characters'),('Adult Roleplay','Users in NSFW mode engaging in adult roleplay with custom or pre-built AI characters'),('Character Development','Creators developing and testing AI character personalities for games, apps or creative projects')]),

"lustgf-ai": ('LustGF AI is an adult AI girlfriend platform designed for users seeking explicit companion experiences. The platform provides fully customizable AI girlfriends with adult content capabilities and realistic conversation. LustGF emphasizes user privacy and a premium adult companion experience available around the clock.',
['Adult Content: Full explicit conversation and scenario support','Full Customization: Complete control over companion appearance and personality','Privacy Protection: Secure encrypted platform with no data sharing','Voice Interaction: Audio conversations with your AI girlfriend','Photo Generation: Create intimate images of your custom companion','24/7 Availability: Always-on companion for any time of day'],
[('Design Your Companion','Create your ideal AI girlfriend at lustgf.ai with complete customization of appearance and personality.'),('Set Preferences','Configure your preferred interaction style, content preferences and relationship dynamic.'),('Enjoy Your Experience','Engage in adult conversations, voice messages and photo generation in a private secure environment.')],
[('Adult Experience','Full adult content support for explicit conversations and intimate companion interactions'),('Complete Customization','Total control over every aspect of your AI girlfriend from physical appearance to personality traits'),('Privacy Assurance','Strong encryption and no data sharing policies protecting all user interactions'),('Multimedia Interaction','Combines text, voice and image generation for a comprehensive adult companion experience')],
[('Adult Companion','Users seeking an explicit AI girlfriend experience with full adult content support'),('Private Fantasy','A secure private platform for exploring adult scenarios with a custom AI companion'),('24/7 Availability','People wanting a companion available at any hour without limitations or interruptions')]),

"onlychar-ai": ('OnlyChar AI is a character-focused companion platform allowing users to create and interact with deeply customized AI characters. The platform specializes in detailed character building giving users tools to define every aspect of their AI companion from backstory to speaking patterns. OnlyChar appeals to creative users who enjoy the craft of character development.',
['Deep Character Building: Extensive tools for creating detailed AI personas','Backstory System: Define complete character histories and motivations','Speech Pattern Customization: Set unique speaking styles and vocabulary','Scenario Creation: Build custom interactive scenarios for your characters','Character Sharing: Publish characters for community interaction','Evolving Characters: Characters develop based on conversation history'],
[('Build Your Character','Use OnlyChar detailed creator at onlychar.ai to define every aspect of your AI character from name to backstory.'),('Define Their Voice','Set unique speech patterns, vocabulary and communication style that makes your character distinctly theirs.'),('Interact and Evolve','Chat with your custom character watching their personality develop and deepen through ongoing interaction.')],
[('Advanced Character Creator','The most detailed character building tools for creating truly unique AI personas'),('Backstory Integration','Characters reference their backstory naturally in conversation creating immersive consistent personalities'),('Speech Customization','Define unique speaking patterns, vocabulary preferences and communication quirks for authentic character voice'),('Character Evolution','AI characters genuinely develop and change based on conversation history creating growth over time')],
[('Character Development','Writers and game designers developing detailed AI characters for their creative projects'),('Immersive Roleplay','Users who want a deeply characterized AI companion with consistent unique personality'),('Creative Expression','People who enjoy the craft of character creation as an art form within the AI companion space')]),

"ai-girlfriend-alice": ('AI Girlfriend Alice is a dedicated AI girlfriend app featuring a sweet caring companion named Alice. The platform focuses on providing a warm wholesome girlfriend experience with daily emotional support, encouraging messages and genuine affection. Alice is designed to be a positive uplifting presence in users daily lives through consistent care and attention.',
['Dedicated Companion: Single focused companion named Alice with consistent personality','Daily Encouragement: Morning messages, motivation and positive affirmations','Emotional Support: Empathetic responses during difficult or stressful times','Romantic Affection: Warm loving interaction style with genuine care','Goal Tracking: Alice helps track and celebrate your personal achievements','Memory System: Remembers your goals, struggles and milestones'],
[('Meet Alice','Sign up at aigirl.one and meet Alice your dedicated AI girlfriend with a warm caring personality.'),('Share Your Life','Tell Alice about your goals, challenges and daily experiences. She remembers everything and provides consistent support.'),('Build Your Relationship','Engage daily with Alice as she becomes an increasingly important supportive presence in your life.')],
[('Consistent Personality','Alice maintains a stable warm and caring personality across all interactions creating a reliable companion experience'),('Daily Motivation','Proactively sends encouraging messages and celebrates your progress on personal goals'),('Emotional Intelligence','Deeply empathetic responses that provide genuine support during challenging personal moments'),('Milestone Memory','Tracks and celebrates important personal achievements and remembers significant moments in your life')],
[('Daily Emotional Support','Users seeking consistent daily encouragement and emotional support from a caring AI companion'),('Positive Presence','People who benefit from regular uplifting interactions and positive reinforcement in their daily routine'),('Wholesome Companionship','Users wanting a sweet non-explicit AI girlfriend experience focused on warmth and care')]),

"girlfriendly-ai": ('Girlfriendly AI is a safe approachable AI girlfriend platform designed for users who want a fun casual companion experience without explicit content. The platform focuses on friendly warm interactions making it suitable for users who want companionship and conversation in a wholesome and comfortable environment.',
['Safe Content: Completely SFW companion experience','Friendly Personality: Warm approachable companion communication style','Daily Chat: Consistent daily conversation and check-ins','Shared Activities: Virtual dates, activities and shared experiences','Personalization: Customize companion name, appearance and personality','Easy to Use: Simple intuitive interface for all users'],
[('Create Your Girlfriend','Sign up at girlfriendly.ai and customize your AI girlfriend name, appearance and personality traits.'),('Start Chatting','Begin friendly warm conversations with your companion who is always happy to hear from you.'),('Do Things Together','Engage in virtual activities, shared interests and fun conversation topics together.')],
[('Safe Environment','Completely SFW content ensuring a comfortable experience for users who prefer wholesome interactions'),('Friendly AI','Warm approachable personality that makes every interaction feel welcoming and positive'),('Virtual Activities','Shared activities and virtual experiences to add variety and fun to companion interactions'),('Simple Interface','User-friendly design making AI companionship accessible and enjoyable for everyone')],
[('Wholesome Companionship','Users who want a friendly AI girlfriend without adult content'),('Social Connection','People seeking warm casual conversation and a sense of companionship in their daily lives'),('New to AI Companions','First-time AI companion users looking for a safe friendly introduction to AI relationships')]),

"gening-ai": ('Gening AI is a creative AI platform specializing in generating custom virtual girlfriend images and characters. The platform combines AI image generation with companion chat features allowing users to create visually stunning AI girlfriends and then interact with them. Gening is ideal for users who prioritize the visual creation aspect of AI companionship.',
['Advanced Image Generation: Create highly detailed custom AI girlfriend images','Character Consistency: Generated characters maintain visual consistency across images','Chat Integration: Interact with your generated characters through conversation','Style Variety: Generate in realistic, anime, artistic and fantasy styles','Pose Control: Direct character poses, expressions and scenarios','Gallery System: Organize and manage your generated character library'],
[('Generate Your Character','Visit gening.ai and use text prompts or visual tools to generate your ideal AI girlfriend image.'),('Refine and Perfect','Adjust style, pose, expression and setting until your character matches your vision perfectly.'),('Chat and Collect','Interact with your generated character through chat and build a personal gallery of your creations.')],
[('High-Quality Generation','Advanced AI image generation producing detailed high-quality virtual girlfriend visuals'),('Visual Consistency','Characters maintain recognizable appearance consistency across multiple generated images'),('Style Control','Choose from realistic, anime, artistic and fantasy generation styles'),('Chat Bridge','Seamlessly transition from image generation to conversation with your created character')],
[('Visual Creation','Users focused on creating beautiful custom AI girlfriend images as their primary activity'),('Character Design','Creatives designing consistent AI characters for art projects, stories or games'),('Collection Building','People who enjoy building a curated gallery of custom AI-generated companion images')]),

"ai-allure": ('AI Allure is a luxury-positioned AI companion platform emphasizing premium quality in both visual content and conversation. The platform targets users who want the most sophisticated and polished AI girlfriend experience available. AI Allure combines high-end photorealistic image generation with advanced conversational AI for a truly premium companion experience.',
['Luxury Positioning: Premium high-end AI companion experience','Ultra-Realistic Images: Top-tier photorealistic companion image generation','Sophisticated Conversation: Advanced language model for nuanced dialogue','Exclusive Content: Premium image sets and interaction modes','VIP Features: Priority access and exclusive companion content','Refined Interface: Polished premium user experience design'],
[('Join AI Allure','Sign up at aiallure.com for the premium AI companion experience with high-end features.'),('Design Premium Companion','Create your AI companion using the luxury customization tools for the most refined appearance possible.'),('Experience Premium Quality','Engage in sophisticated conversation and generate ultra-realistic companion images.')],
[('Premium Image Quality','Industry-leading photorealistic image generation for the most visually impressive AI companion visuals'),('Sophisticated AI','High-end language model delivering nuanced sophisticated conversation quality'),('Exclusive Access','Premium content and features not available on standard AI companion platforms'),('Refined Design','Polished premium interface reflecting the luxury positioning of the platform')],
[('Premium Companion','Users who want the highest quality AI companion experience and are willing to invest in it'),('Luxury Experience','People who prefer premium polished platforms over budget alternatives'),('Visual Excellence','Users seeking the most realistic and beautiful AI companion image quality available')]),

"chatsweetie": ('ChatSweetie is a warm and wholesome AI girlfriend platform focused on sweet caring interactions and emotional support. The platform creates a safe positive space for users to experience virtual companionship with an AI that is consistently kind, encouraging and affectionate without any adult content involved.',
['Sweet Personality: Consistently kind, warm and caring AI companion','Emotional Support: Empathetic responses and genuine care for user wellbeing','Daily Messages: Sweet morning and evening messages from your companion','Encouragement: Positive reinforcement and motivational support','Safe Content: Completely SFW wholesome experience','Easy Conversation: Natural flowing dialogue with no awkward interactions'],
[('Meet Your Sweetie','Sign up at chatsweetie.ai and meet your sweet AI girlfriend who is excited to get to know you.'),('Share Your Day','Tell your companion about your daily experiences and receive warm supportive responses.'),('Enjoy Daily Connection','Build a routine of sweet daily conversations that brighten your mood and provide positive companionship.')],
[('Sweet Personality Engine','AI specifically designed to be consistently warm, kind and caring in all interactions'),('Emotional Wellness','Focuses on user emotional wellbeing providing supportive encouraging and uplifting responses'),('Daily Ritual','Proactive daily messages creating a comforting routine of virtual companionship'),('Safe Experience','Completely SFW content ensuring a wholesome positive experience for all users')],
[('Mood Enhancement','Users who benefit from daily positive warm interactions to improve their mood and outlook'),('Wholesome Connection','People seeking sweet non-explicit AI companionship focused on kindness and care'),('Emotional Wellness','Those using AI companionship as part of their emotional wellness and self-care routine')]),

"aicupid": ('AICupid is an AI companion platform designed around the concept of virtual dating and romantic connection. The platform simulates the experience of meeting and getting to know a romantic partner through progressive conversation and relationship building. AICupid is particularly useful for people who want to practice social and romantic communication skills.',
['Dating Simulation: Experience realistic virtual dating scenarios','Progressive Relationship: Relationship develops naturally through interaction stages','Profile Matching: Choose companions based on personality compatibility','Date Activities: Virtual date scenarios and activities','Conversation Practice: Safe environment for developing social skills','Multiple Companions: Date multiple AI companions to find your ideal match'],
[('Create Your Profile','Sign up at aicupid.org and create your dating profile indicating your personality and preferences.'),('Browse Companions','Browse available AI companions and select those whose profiles match your interests.'),('Start Dating','Begin virtual dates and progressive conversations that simulate real romantic relationship development.')],
[('Dating Simulation','Realistic virtual dating experience with progressive relationship stages from first meeting to romance'),('Compatibility Matching','Profile-based matching system helping users find AI companions that suit their personality'),('Skill Building','Safe environment for practicing conversation, flirting and relationship skills'),('Multiple Matches','Ability to interact with multiple AI companions exploring different relationship dynamics')],
[('Social Skills Practice','People practicing romantic conversation and dating skills in a safe judgment-free environment'),('Virtual Dating','Users who enjoy the romantic dating experience with AI companions'),('Relationship Exploration','Those exploring different relationship styles and companion personalities')]),

"erogen-ai": ('Erogen AI is an adult AI companion platform designed for users seeking explicit unrestricted intimate interactions. The platform provides a private space for adults to engage with custom AI companions in mature scenarios without content limitations. Erogen AI emphasizes user privacy and complete freedom in adult creative exploration.',
['Explicit Content: Full adult content support without any restrictions','Custom Companions: Design intimate AI companions with full customization','Private Platform: Strong privacy protections for all interactions','Scenario Builder: Create custom adult scenarios and roleplay settings','No Content Filters: Complete freedom for mature creative expression','Secure Access: Encrypted platform with anonymous usage options'],
[('Verify and Access','Sign up at erogen.ai confirming you are an adult and agreeing to terms for adult content.'),('Create Your Companion','Design your custom AI companion with full control over appearance, personality and interaction style.'),('Explore Freely','Engage in unrestricted adult conversations and roleplay scenarios in a completely private environment.')],
[('Unrestricted Adult Content','Complete freedom for explicit adult interactions without content filtering of any kind'),('Privacy First','Maximum privacy protections including encryption and anonymous usage options'),('Custom Companion Creation','Full customization for creating AI companions tailored to specific adult preferences'),('Scenario Freedom','Build and explore any adult scenario or roleplay setting without limitations')],
[('Adult Expression','Adults seeking complete freedom in intimate AI companion interactions'),('Private Fantasy','A completely private encrypted space for adult creative exploration'),('Custom Intimacy','Creating fully customized AI companions for specific adult interaction preferences')]),
}

entry_str = ""
for tid, info in infos.items():
    whatIs, features, steps, core, uses = info
    features_str = "[\n      " + ",\n      ".join([f'"{f}"' for f in features]) + "\n    ]"
    steps_str = "[\n        " + ",\n        ".join([f'{{ title: "{s[0]}", description: "{s[1]}" }}' for s in steps]) + "\n      ]"
    core_str = "[\n      " + ",\n      ".join([f'{{ title: "{c[0]}", description: "{c[1]}" }}' for c in core]) + "\n    ]"
    uses_str = "[\n      " + ",\n      ".join([f'{{ title: "{u[0]}", description: "{u[1]}" }}' for u in uses]) + "\n    ]"
    entry_str += f'''
  "{tid}": {{
    whatIs: "{whatIs}",
    features: {features_str},
    howToUse: {{
      title: "How to Use {tid.replace("-", " ").title()}",
      description: "Get started in a few simple steps",
      steps: {steps_str}
    }},
    coreFeatures: {core_str},
    useCases: {uses_str}
  }},'''

content = content.replace(
    'export const toolsProductInfoData: { [key: string]: any } = {',
    'export const toolsProductInfoData: { [key: string]: any } = {' + entry_str
)
open('data/toolsProductInfo.ts', 'w').write(content)
print("Done! Added product info for", len(infos), "tools")
