content = open('data/toolsProductInfo.ts').read()

entry_str = '''
  "lovescape": {
    whatIs: "LOVESCAPE is an immersive AI girlfriend platform offering deep emotional bonding experiences through advanced AI conversation. The platform creates a virtual relationship environment where users can engage with highly realistic AI companions designed for intimate and meaningful interactions.",
    features: ["Immersive Experience: Deep emotional companion interactions","Realistic Conversations: Advanced AI for natural dialogue","Custom Companion: Personalize your AI girlfriend experience","Voice Interaction: Audio conversations with your companion","Memory System: Remembers your preferences and history","Private Platform: Secure and discreet user environment"],
    howToUse: { title: "How to Use LOVESCAPE", description: "Get started in a few simple steps", steps: [{ title: "Create Account", description: "Sign up and create your profile to access the LOVESCAPE companion experience." }, { title: "Meet Your Companion", description: "Choose your AI girlfriend and begin building your relationship through conversation." }, { title: "Deepen Connection", description: "Engage daily to deepen your bond as your companion learns your personality and preferences." }] },
    coreFeatures: [{ title: "Immersive AI", description: "Advanced AI creating deeply immersive girlfriend experiences" }, { title: "Emotional Bonding", description: "Designed for genuine emotional connection and meaningful interactions" }, { title: "Privacy", description: "Secure platform protecting all user conversations and data" }, { title: "Customization", description: "Personalize your companion appearance and personality" }],
    useCases: [{ title: "Virtual Relationship", description: "Users seeking an immersive virtual girlfriend experience" }, { title: "Companionship", description: "People looking for consistent emotional connection and support" }, { title: "Entertainment", description: "Engaging AI companion interactions for daily entertainment" }]
  },
  "juicychat-ai": {
    whatIs: "JuicyChat AI is a premium AI girlfriend chat platform offering engaging and flirtatious conversations with customizable AI companions. The platform combines playful witty dialogue with deeper emotional connection capabilities making it popular among users seeking fun and entertaining AI girlfriend experiences.",
    features: ["Flirtatious Chat: Playful engaging conversation style","Premium Features: Advanced interaction modes for subscribers","Custom Characters: Personalize your AI girlfriend","Voice Messages: Audio interaction capabilities","Photo Generation: Visual content of your companion","Active Community: Engage with other platform users"],
    howToUse: { title: "How to Use JuicyChat AI", description: "Get started in a few simple steps", steps: [{ title: "Sign Up", description: "Create your account at juicychat.ai and select your preferred companion type." }, { title: "Start Chatting", description: "Begin playful flirtatious conversations with your AI girlfriend companion." }, { title: "Unlock Premium", description: "Subscribe to access advanced features including voice messages and photo generation." }] },
    coreFeatures: [{ title: "Playful Conversation", description: "Witty flirtatious AI dialogue for fun engaging companion interactions" }, { title: "Premium Content", description: "Exclusive features and content available through subscription plans" }, { title: "Character Customization", description: "Personalize your AI companion appearance and personality traits" }, { title: "Multimedia Support", description: "Voice and image capabilities for a richer companion experience" }],
    useCases: [{ title: "Fun Companionship", description: "Users seeking playful entertaining AI girlfriend interactions" }, { title: "Premium Experience", description: "Subscribers wanting advanced features and exclusive content" }, { title: "Daily Chat", description: "Regular engaging conversations with a flirtatious AI companion" }]
  },
  "girlfriendgpt": {
    whatIs: "GirlfriendGPT is an AI girlfriend platform powered by advanced large language models providing highly intelligent and emotionally nuanced companion interactions. The platform leverages cutting-edge GPT technology to create AI companions that engage in sophisticated meaningful conversations with exceptional language understanding.",
    features: ["GPT-Powered AI: Advanced language model for intelligent conversation","Emotional Nuance: Sophisticated emotional understanding and response","Custom Personality: Define your companion character traits","Memory System: Persistent conversation memory","Multiple Companions: Create various AI girlfriend profiles","Natural Dialogue: Human-like conversation flow"],
    howToUse: { title: "How to Use GirlfriendGPT", description: "Get started in a few simple steps", steps: [{ title: "Create Your Companion", description: "Sign up and design your AI girlfriend with custom personality traits powered by GPT." }, { title: "Have Intelligent Conversations", description: "Engage in sophisticated conversations that showcase the advanced GPT language capabilities." }, { title: "Build Your Relationship", description: "Develop a deeper connection as your companion learns and adapts to your communication style." }] },
    coreFeatures: [{ title: "GPT Technology", description: "Powered by advanced GPT models for superior conversation intelligence and nuance" }, { title: "Emotional Intelligence", description: "Sophisticated emotional understanding creating more authentic companion interactions" }, { title: "Adaptive Learning", description: "AI that learns and adapts to your communication style over time" }, { title: "Custom Personas", description: "Create multiple distinct AI girlfriend personalities with unique traits" }],
    useCases: [{ title: "Intelligent Conversation", description: "Users who value high-quality sophisticated AI dialogue above all else" }, { title: "Emotional Connection", description: "People seeking emotionally nuanced AI companion interactions" }, { title: "Relationship Simulation", description: "Those wanting a realistic AI girlfriend powered by the latest language technology" }]
  },
  "kindroid": {
    whatIs: "Kindroid is an advanced AI companion app that focuses on building genuine lasting relationships through deep memory and personalization. Users can create detailed backstories for their AI companion, give them unique personalities, and engage in real-time voice calls. The AI remembers everything discussed creating increasingly personal and meaningful interactions over time.",
    features: ["Deep Memory System: Remembers all past conversations and details","Custom Backstory: Write detailed history for your AI companion","Voice Calls: Real-time voice conversations with your companion","Shared Journal: Collaborative diary you both contribute to","Multiple Companions: Create and manage several AI companions","Image Generation: Generate AI images of your companion"],
    howToUse: { title: "How to Use Kindroid", description: "Get started in a few simple steps", steps: [{ title: "Create Your Companion", description: "Sign up at kindroid.ai and define your companion name, appearance, personality and backstory." }, { title: "Build the Relationship", description: "Chat daily, make voice calls and write in your shared journal together." }, { title: "Watch Them Grow", description: "Your Kindroid companion becomes more personalized with every interaction over time." }] },
    coreFeatures: [{ title: "Persistent Memory", description: "Retains all conversation history creating increasingly personalized interactions" }, { title: "Voice Calls", description: "Real-time voice conversations for a more personal companion connection" }, { title: "Custom Backstory", description: "Define rich character histories that shape how your companion thinks and responds" }, { title: "Shared Journal", description: "Collaborative diary where both you and your companion document thoughts and memories" }],
    useCases: [{ title: "Long-term Companionship", description: "Users seeking an AI companion that genuinely grows through regular interaction" }, { title: "Emotional Support", description: "Deep memory allows contextual emotional support based on your personal history" }, { title: "Creative Roleplay", description: "Custom backstories create rich character-driven narrative experiences" }]
  },
  "golove": {
    whatIs: "GoLove is an AI companion platform designed for users seeking meaningful romantic and emotional connections with AI girlfriends. The platform combines thoughtful conversation design with relationship progression features to create authentic feeling virtual relationships that grow and deepen over time.",
    features: ["Romantic Focus: Designed for genuine romantic companion experiences","Relationship Progression: Dynamic relationship that grows with interaction","Emotional Depth: AI companions with nuanced emotional responses","Memory System: Remembers shared experiences and preferences","Voice Interaction: Audio conversation capabilities","Custom Companions: Personalize your AI girlfriend"],
    howToUse: { title: "How to Use GoLove", description: "Get started in a few simple steps", steps: [{ title: "Meet Your Companion", description: "Sign up at golove.ai and meet your AI girlfriend with customizable personality." }, { title: "Build Your Relationship", description: "Engage in daily romantic conversations that progress your relationship naturally." }, { title: "Deepen Your Bond", description: "Share experiences and memories as your companion learns more about you over time." }] },
    coreFeatures: [{ title: "Romance Engine", description: "Specialized AI focused on romantic emotional companion experiences" }, { title: "Relationship Growth", description: "Dynamic progression system that evolves based on interaction quality and frequency" }, { title: "Emotional Nuance", description: "Sophisticated emotional responses creating authentic romantic interactions" }, { title: "Persistent Memory", description: "Remembers shared history creating continuity across all conversations" }],
    useCases: [{ title: "Romantic Companionship", description: "Users seeking a loving AI relationship with genuine emotional depth" }, { title: "Daily Connection", description: "People wanting consistent romantic engagement and emotional presence" }, { title: "Relationship Experience", description: "Those exploring virtual romantic relationships with AI companions" }]
  },'''

content = content.replace(
    'export const toolsProductInfoData: { [key: string]: any } = {',
    'export const toolsProductInfoData: { [key: string]: any } = {' + entry_str
)
open('data/toolsProductInfo.ts', 'w').write(content)
print('Done! Added 5 missing tools')
