content = open('data/toolsProductInfo.ts').read()

infos = {
"manus-ai": ('Manus AI is a groundbreaking autonomous AI agent platform developed by Butterfly Effect and acquired by Meta in late 2025 for an estimated 2 billion dollars. Unlike traditional AI assistants that only answer questions, Manus independently executes complex multi-step tasks by browsing the web, writing and running code, analyzing data, creating documents and interacting with external services. The platform operates asynchronously in the cloud meaning users give a goal and Manus delivers completed results without requiring constant supervision. It integrates with Notion, Gmail, Slack and other platforms.',['Autonomous Task Execution: Completes complex multi-step tasks without human intervention','Web Browsing: Independently searches and extracts information from websites','Code Writing and Execution: Writes and runs code in a sandbox environment','Document Creation: Produces polished reports, presentations and documents','Data Analysis: Analyzes datasets and creates charts and insights automatically','Multi-Agent System: Uses specialized agents for different task types simultaneously','Tool Integrations: Connects with Notion, Gmail, Slack and other platforms','Live Task Streaming: Watch the AI work in real time through the Manus Computer view'],[('Define Your Goal','Visit manus.im and describe the complex task you want completed in plain language. Be specific about the desired output format.'),('Let Manus Work','Manus breaks your goal into subtasks and executes them autonomously using web browsing, code execution and document creation tools. Watch progress in real time.'),('Receive Your Results','Manus delivers completed results as files, reports or structured outputs ready for immediate use. Review and iterate if needed.')],[('Autonomous Execution','The defining feature of Manus is true autonomous multi-step task completion without requiring human guidance at each step'),('Manus Computer View','Live streaming dashboard showing exactly what the AI is doing including websites visited, code written and documents created in real time'),('Multi-Agent Architecture','Multiple specialized AI agents work simultaneously on different aspects of a task selecting the best model for each subtask'),('Cross-Platform Integration','Seamless integration with productivity tools including Notion, Gmail and Slack enabling AI to take actions across your existing workflow')],[('Research and Analysis','Professionals automating complex research tasks that previously required hours of manual web searching, data collection and report writing'),('Code Development','Developers using Manus to prototype applications, write scripts and automate coding tasks with minimal manual input'),('Business Workflows','Teams using Manus to automate recurring business processes including data collection, report generation and email management')]),

"unlucid-ai": ('Unlucid AI is a creative AI image and video generation platform specializing in surreal, dreamlike and artistic visuals created from text prompts. The platform focuses on unique aesthetic outputs that go beyond standard image generation offering otherworldly and imaginative results. Unlucid is popular with artists and creators who want distinctive AI-generated visuals that stand out from typical AI art.',['Surreal Image Generation: Create dreamlike and surreal AI artwork from text','Video Generation: Produce AI-generated videos with unique visual styles','Unique Aesthetics: Distinctive visual style unlike standard AI generators','Multiple Styles: Various surreal and artistic generation modes','High Quality Output: Professional resolution image and video output','Creative Freedom: Minimal restrictions for experimental artistic expression'],[('Describe Your Vision','Visit unlucid.ai and write a creative text prompt describing the surreal or dreamlike image or video you want to generate.'),('Generate Your Art','Submit your prompt and Unlucid AI generates a unique surreal visual with its distinctive aesthetic style.'),('Download and Share','Download your artwork or video for use in creative projects.')],[('Surreal AI Engine','Specialized AI generation model producing distinctive dreamlike and surreal visuals not available on standard generation platforms'),('Video Generation','Creates AI-generated video content with unique surreal visual aesthetics for creative and artistic projects'),('Unique Aesthetic','Platform-specific visual style creating outputs with a distinctive otherworldly quality'),('Creative Freedom','Minimal content restrictions allowing experimental and boundary-pushing artistic image and video creation')],[('Surreal Art Creation','Artists and creatives generating unique surreal and dreamlike imagery for art projects and personal expression'),('Video Content','Content creators producing distinctive AI-generated video content with unique visual aesthetics'),('Artistic Exploration','Users exploring the boundaries of AI generation through experimental surreal and abstract prompts')]),

"spicychat-ai": ('SpicyChat AI is an uncensored AI chatbot platform developed by NextDay AI Incorporated featuring over 850000 community-created characters for creative roleplay and adult conversations. The platform uses advanced language models including the SpicyXL model with up to 141 billion parameters for sophisticated responses. SpicyChat stands out for its generous free tier that includes NSFW chat access, Semantic Memory 2.0 for cross-session recall, and cross-platform availability on web, iOS and Android. With over 2 million registered members it is one of the largest AI companion communities.',['Massive Character Library: Over 850000 AI characters across every genre and personality type','Uncensored Roleplay: Adult-oriented conversations without content restrictions','Semantic Memory 2.0: AI remembers preferences and story elements across multiple sessions','SpicyXL Model: Up to 141 billion parameter AI model for sophisticated responses','Voice Mode: Real-time voice interaction with AI characters','Cross-Platform: Available on web, iOS and Android','Community Creation: Users create and share their own AI characters','Free NSFW Access: Adult content available on the free tier'],[('Sign Up Free','Visit spicychat.ai and create a free account. The free tier gives immediate access to the character library and uncensored chat without a credit card.'),('Choose or Create a Character','Browse 850000 plus community characters or build your own with custom name, personality, appearance and backstory.'),('Start Chatting','Begin your roleplay or conversation. Upgrade to unlock Semantic Memory 2.0 and larger context windows for longer sessions.')],[('SpicyXL AI Model','Powers conversations with up to 141 billion parameters delivering sophisticated contextually aware responses on premium plans'),('Semantic Memory 2.0','Automatically generates and retains memories from conversations allowing characters to recall preferences and story details across sessions'),('Character Creator','Extensive tools for building custom AI characters with detailed personality traits, appearance, backstory and behavioral instructions'),('Community Library','850000 plus user-created characters continuously expanding through community contributions across every genre and theme')],[('Adult Roleplay','Adults seeking uncensored creative roleplay with highly customizable AI characters in a platform built for mature content'),('Interactive Storytelling','Writers and creatives using AI characters to develop narrative scenarios and explore story ideas through immersive dialogue'),('AI Companionship','Users seeking ongoing companionship with AI characters that remember past conversations and build consistent relationships')]),

"vheer-ai": ('Vheer AI is an advanced AI image generation platform that creates high-quality realistic and artistic images from text prompts. The platform offers multiple generation styles ranging from photorealistic to artistic and stylized outputs. Vheer focuses on delivering professional quality results with fine-grained control over style, composition and character details making it suitable for creators, designers and digital artists.',['Text to Image: Generate detailed images from text descriptions','Multiple Styles: Realistic, artistic, anime and fantasy generation options','High Resolution: Professional quality image output','Character Control: Detailed control over character appearance and scenes','Fast Generation: Quick image rendering with advanced AI','Commercial License: Generated images available for commercial use'],[('Write Your Prompt','Visit vheer.com and describe the image you want to create with detailed text. Include style, subject, colors and composition details.'),('Select Your Style','Choose from available generation styles including realistic, artistic or anime to match your creative vision.'),('Generate and Download','Generate your image and download the high-resolution result for personal or commercial use.')],[('Advanced Generation AI','Powerful AI image generation model producing detailed high-quality results across multiple visual styles'),('Style Control','Comprehensive style selection allowing users to target specific aesthetic outcomes from photorealistic to stylized'),('Character Detail','Fine-grained control over character appearance, poses and scene composition for precise creative output'),('Commercial Availability','Generated images available for commercial use making Vheer suitable for business and professional creative projects')],[('Digital Art Creation','Artists and creatives generating original artwork and illustrations using AI image generation technology'),('Content Marketing','Marketers creating custom visual content for campaigns, social media and digital advertising'),('Concept Visualization','Designers and developers using Vheer to quickly visualize concepts and ideas before production')]),

"dreamina-ai": ('Dreamina AI is CapCut powerful AI image and video generation platform that creates stunning visuals from text descriptions. Backed by ByteDance the parent company of TikTok and CapCut, Dreamina combines professional-grade AI generation technology with an easy-to-use interface accessible to creators of all skill levels. The platform supports both image and video generation with multiple art styles and high resolution output making it one of the most capable AI creative tools available.',['Text to Image: Generate high-quality images from detailed text descriptions','Video Generation: Create short AI-generated videos from text prompts','Multiple Art Styles: Realistic, anime, artistic and fantasy generation modes','High Resolution: Professional quality image output up to 4K resolution','CapCut Integration: Seamless workflow with CapCut video editing tools','Commercial Use: Generated content suitable for commercial creative projects'],[('Access Dreamina','Visit dreamina.capcut.com and sign in with your CapCut or TikTok account for instant access.'),('Describe Your Vision','Write a detailed text prompt describing the image or video you want to create. Include style, subject, colors and mood for best results.'),('Generate and Use','Generate your content and download it directly or send it to CapCut for further editing and use in your creative projects.')],[('AI Image Generation','Professional quality text-to-image generation powered by ByteDance advanced AI technology'),('Video Creation','Text-to-video generation producing short creative clips suitable for social media and content creation'),('Style Variety','Multiple generation styles from photorealistic to anime and artistic allowing diverse creative output'),('Platform Integration','Deep integration with CapCut ecosystem enabling seamless creative workflows from generation to editing to publishing')],[('Social Media Content','Content creators generating custom images and videos for TikTok, Instagram and other social platforms'),('Creative Projects','Artists and designers using Dreamina to generate visual assets and concept art for their projects'),('Marketing Materials','Businesses creating custom visual content for advertising, social media and digital marketing campaigns')]),

"pica-ai": ('Pica AI is a comprehensive AI photo editing and enhancement platform specializing in face swapping, background removal, image restoration and creative photo effects. The platform uses advanced computer vision and AI models to deliver professional-quality photo editing results accessible to non-professionals. Pica AI is particularly popular for its realistic face swap technology and its ability to transform ordinary photos into professional-quality portraits.',['AI Face Swap: Realistic face swapping in photos with natural results','Background Removal: Instant AI-powered background removal and replacement','Photo Enhancement: Improve image quality, sharpness and color automatically','Face Beautification: AI skin smoothing, feature enhancement and portrait retouching','Style Transfer: Apply artistic styles and filters to photos using AI','Object Removal: Remove unwanted objects from photos seamlessly'],[('Upload Your Photo','Visit pica-ai.com and upload the photo you want to edit or enhance.'),('Choose Your Edit','Select from face swap, background removal, enhancement or style transfer based on your creative goal.'),('Download Results','Review your AI-edited photo and download the high-resolution result for personal or commercial use.')],[('AI Face Swap','Industry-leading face swap technology producing realistic natural-looking results for photos and creative projects'),('Smart Background Removal','One-click AI background removal with precise edge detection for clean professional cutouts'),('Portrait Enhancement','Comprehensive portrait retouching including skin smoothing, color correction and feature enhancement'),('Batch Processing','Process multiple images simultaneously saving significant time for photographers and content creators')],[('Content Creation','Social media creators and influencers using AI photo effects for creative and entertaining content'),('Professional Photography','Photographers using AI enhancement tools to quickly improve client photos and deliver professional results'),('Personal Use','Casual users transforming personal photos with face swaps, enhancements and creative effects for fun')]),

"agnes-ai": ('Agnes AI is an intelligent AI assistant and agent platform helping users with research, writing, task automation and information retrieval through conversational AI. The platform provides a capable AI agent for productivity tasks including document analysis, content creation, web research and complex question answering. Agnes AI acts as a personal AI assistant that handles diverse tasks efficiently.',['AI Research: Automated web research and information gathering','Writing Support: Assistance with content creation and editing','Task Automation: Automate repetitive productivity tasks','Document Analysis: Analyze and summarize uploaded documents','Question Answering: Accurate responses to complex questions','Conversation Memory: Remembers context across conversation sessions'],[('Start a Conversation','Visit agnes-ai.com and begin a conversation with Agnes by describing what you need help with.'),('Work Together','Ask Agnes to help with research, writing, analysis or any productivity task. Provide context for better results.'),('Get Results','Receive detailed helpful responses and outputs. Continue the conversation to refine results or tackle new tasks.')],[('Conversational AI Agent','Natural language AI agent capable of understanding and executing diverse research and productivity requests autonomously'),('Document Intelligence','Analyzes and extracts insights from uploaded documents providing summaries and answering specific questions'),('Writing Assistant','Helps with all types of content creation from emails to reports with suggestions and complete drafts'),('Research Capability','Assists with gathering, organizing and synthesizing information on any topic for research and analysis purposes')],[('Research Tasks','Professionals and students needing AI assistance with gathering and organizing information for projects'),('Content Creation','Writers and marketers using AI to assist with creating articles, emails and other written content'),('Productivity Enhancement','Users automating routine information tasks and getting quick answers to questions during their workflow')]),

"pixnova-ai": ('Pixnova AI is a creative AI image and video generation platform producing high-quality artwork, illustrations and multimedia content from text descriptions. The platform offers multiple art styles and high-resolution output suitable for both personal and commercial creative projects. Pixnova focuses on delivering consistent quality across a wide range of artistic styles for images and video content.',['Text to Image: Generate high-quality images from text descriptions','Video Generation: Create AI-generated videos from text prompts','Art Style Variety: Multiple artistic styles from realistic to illustrated','High Resolution: Professional quality image and video output','Character Creation: Generate detailed character illustrations','Commercial License: Images and videos available for commercial use'],[('Enter Your Prompt','Visit pixnova.ai and write a detailed text description of the image or video you want to create.'),('Select Your Style','Choose from available art styles to match the aesthetic you want for your content.'),('Generate and Download','Generate your content and download the high-resolution result for your creative project.')],[('Creative AI Engine','Powerful text-to-image and text-to-video AI producing diverse high-quality artistic outputs'),('Style Control','Comprehensive art style selection allowing users to achieve specific aesthetic outcomes consistently'),('Video Generation','Creates AI-generated video content from text descriptions for diverse creative applications'),('Commercial Ready','Generated content available for commercial use making Pixnova suitable for business applications')],[('Digital Art','Artists using AI generation to create original artwork and illustrations for personal and commercial use'),('Video Content','Creators producing AI-generated video content for social media, marketing and creative projects'),('Content Marketing','Marketers creating unique custom visuals and videos for campaigns and digital marketing')])
}

entry_str = ""
skipped = 0
for tid, info in infos.items():
    if '"' + tid + '": {' in content:
        print(f"SKIP {tid} - already exists")
        skipped += 1
        continue
    whatIs, features, steps, core, uses = info
    features_str = "[\n      " + ",\n      ".join([f'"{f}"' for f in features]) + "\n    ]"
    steps_str = "[\n        " + ",\n        ".join([f'{{ title: "{s[0]}", description: "{s[1]}" }}' for s in steps]) + "\n      ]"
    core_str = "[\n      " + ",\n      ".join([f'{{ title: "{c[0]}", description: "{c[1]}" }}' for c in core]) + "\n    ]"
    uses_str = "[\n      " + ",\n      ".join([f'{{ title: "{u[0]}", description: "{u[1]}" }}' for u in uses]) + "\n    ]"
    name = tid.replace("-", " ").title()
    entry_str += f'''
  "{tid}": {{
    whatIs: "{whatIs}",
    features: {features_str},
    howToUse: {{
      title: "How to Use {name}",
      description: "Get started in a few simple steps",
      steps: {steps_str}
    }},
    coreFeatures: {core_str},
    useCases: {uses_str}
  }},'''

if entry_str:
    content = content.replace(
        'export const toolsProductInfoData: { [key: string]: any } = {',
        'export const toolsProductInfoData: { [key: string]: any } = {' + entry_str
    )
    open('data/toolsProductInfo.ts', 'w').write(content)
    print(f"Added {len(infos) - skipped} entries, skipped {skipped}")
else:
    print("Nothing to add")
