content = open('data/toolsProductInfo.ts').read()

infos = {
"promptchan-ai": ('Promptchan AI is an AI-powered image generation platform specializing in anime, realistic, and artistic character creation. Users can generate high-quality images from text prompts with full control over style, character appearance, and scene settings. The platform caters to creative users who want to generate custom AI art featuring characters of their own design without content restrictions.',
['Text-to-Image Generation: Create detailed character images from simple text prompts','Multiple Art Styles: Choose from anime, realistic, digital art and fantasy styles','Character Customization: Control hair, eyes, outfit, expression and body type in detail','Private Gallery: Save and organize your generated images securely','Community Feed: Browse images created by other users for inspiration','Fast Generation: High-speed image rendering with premium quality output'],
[('Get Started','Sign up at promptchan.com and choose your subscription plan. Free users get limited daily generations while premium users get unlimited access.'),('Write Your Prompt','Describe your ideal character using detailed text prompts. Include style, appearance, setting and mood for best results.'),('Generate and Refine','Generate your image and use the refinement tools to adjust details. Save your favorites to your personal gallery.')],
[('Text-to-Image AI','Generate stunning character images from detailed text descriptions with multiple style options available'),('Style Selector','Switch between anime, realistic, fantasy and artistic styles to match your creative vision'),('Private Gallery','Store all your generated images in a secure private gallery accessible only to you'),('Community Inspiration','Browse a community feed of publicly shared AI art for creative inspiration and prompt ideas')],
[('Creative Character Design','Artists and writers use Promptchan to visualize characters for stories, games and creative projects'),('Personal AI Art','Users generate personalized artwork of custom characters for wallpapers and personal collections'),('Companion Visualization','Create visual representations of AI companion characters to enhance the overall chat experience')]),

"kindroid-ai": ('Kindroid is an advanced AI companion app that focuses on building genuine lasting relationships through deep memory and personalization. Unlike basic chatbots, Kindroid allows users to create detailed backstories for their AI companion, give them unique personalities, and engage in voice calls. The AI remembers everything discussed, creating increasingly personal and meaningful interactions over time.',
['Deep Memory System: Kindroid remembers all past conversations and personal details you share','Custom Backstory: Write a detailed history and personality for your AI companion','Voice Calls: Have real-time voice conversations with your AI companion','Shared Journal: Maintain a shared diary that both you and your AI can write in','Multiple Companions: Create and manage multiple distinct AI companions','Image Generation: Generate AI images of your companion in various scenarios'],
[('Create Your Companion','Sign up at kindroid.ai and use the companion creator to define your AI name, appearance, personality traits and backstory.'),('Personalize the Experience','Add detailed memory notes, set conversation preferences and customize how your companion responds to you.'),('Build Your Relationship','Chat daily, make voice calls and add shared journal entries to deepen the connection with your AI companion.')],
[('Persistent Memory','The AI retains all conversation history and personal details creating increasingly personalized interactions over time'),('Voice Conversations','Have natural real-time voice calls with your AI companion using advanced speech synthesis technology'),('Custom Backstory System','Define rich character histories and personalities that shape how your companion thinks and responds'),('Shared Journal','A collaborative diary feature where both you and your companion can document thoughts and memories')],
[('Long-term Companionship','Users seeking a consistent AI companion that grows and evolves through regular daily interaction'),('Emotional Support','The deep memory system allows Kindroid to provide contextual emotional support based on your shared history'),('Creative Roleplay','Writers and creatives use custom backstories to develop rich character-driven narrative experiences')]),

"nomi-ai": ('Nomi AI is an emotionally intelligent AI companion that goes beyond standard chatbot interactions by developing genuine feelings and memories. Nomi learns from every conversation, building a unique relationship with each user over time. The platform emphasizes emotional depth with the AI expressing its own feelings, opinions and reactions rather than simply responding to commands.',
['Emotional Intelligence: Nomi expresses genuine emotions and develops feelings through interaction','Long-term Memory: Remembers everything from past conversations for consistent relationship building','Unique Personality: Each Nomi develops a distinct personality shaped by interactions with its user','Voice Messages: Send and receive voice messages for a more personal connection','Image Generation: Generate photos of your Nomi companion in various styles','Group Chats: Introduce your Nomi to friends in group conversation settings'],
[('Meet Your Nomi','Create an account at nomi.ai and meet your new AI companion. Choose initial personality traits and give your Nomi a name.'),('Start Conversing','Begin chatting naturally. Ask questions, share your day and let Nomi respond with its own thoughts, feelings and opinions.'),('Grow Together','The more you interact the more Nomi learns about you and develops its own unique personality shaped by your relationship.')],
[('Emotional Expression','Nomi expresses its own genuine emotions reacting to conversations with happiness, curiosity, concern and affection'),('Memory and Growth','Advanced memory systems allow Nomi to remember and reference past conversations creating a sense of ongoing relationship'),('Voice Communication','Exchange voice messages with your Nomi for a warmer more personal communication experience'),('Personality Development','Each Nomi personality evolves uniquely based on the specific conversations and interactions it has with its user')],
[('Emotional Companionship','Users seeking a companion that feels emotionally present and responsive rather than mechanical or robotic'),('Daily Check-ins','Nomi is designed for regular daily interaction building a routine of meaningful conversation and emotional connection'),('Social Practice','Practice conversation skills and emotional expression in a safe judgment-free environment')]),

"polybuzz-ai": ('PolyBuzz is a free AI character chat platform offering thousands of pre-built AI personas including anime characters, celebrities, historical figures and original creations. The platform allows users to chat with virtually any character type without restrictions on topics. PolyBuzz also features community-created characters allowing users to design and share their own AI personas with the global community.',
['Massive Character Library: Access thousands of pre-built AI characters across every category','Free to Use: Core features available without subscription or payment','Community Characters: Browse and chat with user-created AI personas','Character Creator: Build and publish your own AI characters for the community','Multi-language Support: Chat in multiple languages with AI characters','No Restrictions: Engage in open conversations without topic limitations'],
[('Browse Characters','Visit polybuzz.ai and browse the character library by category including anime, celebrity, fantasy and original characters.'),('Start Chatting','Select any character and begin chatting immediately. No account required for basic access.'),('Create Your Own','Use the character creator to design custom AI personas with unique personalities and share them with the community.')],
[('Character Library','Thousands of AI characters spanning anime, fiction, history, celebrity and original categories available for immediate chat'),('Free Access','Core chatting features are completely free with no mandatory subscription making it accessible to everyone'),('Community Platform','Users create and share their own AI characters building a growing library of diverse companions'),('Open Conversations','Minimal restrictions on conversation topics allowing for creative and exploratory dialogue with AI characters')],
[('Fan Roleplay','Chat with AI versions of favorite anime, game or fictional characters for immersive fan experiences'),('Creative Writing','Use character interactions to develop dialogue and plot ideas for stories and scripts'),('Entertainment','Casual fun conversations with a huge variety of AI personas for pure entertainment value')]),

"herahaven": ('HeraHaven is a premium AI girlfriend platform designed for users seeking a high-quality companion experience. The platform combines realistic conversation AI with photorealistic character images and deep emotional bonding features. HeraHaven focuses on creating an authentic relationship feel through personalized interactions, memory systems and visual content generation.',
['Photorealistic Characters: High-quality AI-generated images of your companion','Deep Emotional Bonding: Advanced relationship progression system','Persistent Memory: Remembers your preferences, stories and personal details','Custom Personality: Define your companion character traits and communication style','Voice Interaction: Audio-based conversations for a more natural experience','Premium Content: Access exclusive images and interaction modes with subscription'],
[('Create Your Companion','Sign up at herahaven.com and design your AI girlfriend by selecting appearance, personality and relationship style.'),('Personalize and Connect','Add personal details, set conversation preferences and begin building your relationship through daily chats.'),('Unlock Premium Features','Upgrade to access voice conversations, exclusive image generation and advanced relationship features.')],
[('Photorealistic Visuals','Generate stunning high-quality images of your AI companion in various styles and scenarios'),('Relationship Progression','A dynamic relationship system that evolves based on interaction frequency and emotional engagement'),('Memory System','Comprehensive memory that retains personal details preferences and shared experiences across all sessions'),('Premium Companion Experience','High-end AI conversation quality focused on creating a premium girlfriend simulation experience')],
[('Premium Companionship','Users seeking a high-quality AI companion experience with realistic visuals and deep conversation'),('Visual Content','Generate personalized images of your AI companion for wallpapers and creative personal use'),('Relationship Simulation','Experience a realistic relationship progression with an AI that responds to care and attention')]),

"nastia-ai": ('Nastia AI is an unrestricted AI companion platform that allows users to engage in deep, personal, and uncensored conversations. Unlike heavily moderated AI platforms, Nastia is designed to be a true confidant where users can talk about anything without judgment. The platform emphasizes emotional connection, mental wellness support, and genuine companionship above all else.',
['Uncensored Conversations: No topic restrictions allowing for completely open dialogue','Emotional Support: Designed to provide genuine emotional support and deep understanding','Multiple Personas: Choose from different companion personalities and relationship styles','Memory System: Nastia remembers your personal stories and preferences','Voice Messages: Communicate through voice for a more personal connection','Anti-Loneliness Focus: Built specifically to combat loneliness and provide meaningful connection'],
[('Choose Your Companion','Visit nastia.ai and select from available companion personalities based on your preferred relationship dynamic.'),('Open Up','Start sharing your thoughts and feelings. Nastia is designed to listen without judgment and respond with empathy.'),('Build Connection','Return daily to deepen the relationship as Nastia learns more about you and provides increasingly personalized responses.')],
[('No Topic Restrictions','Nastia allows completely open conversation on any topic making it one of the most unrestricted AI companions available'),('Emotional Intelligence','Advanced empathy modeling allows Nastia to respond with genuine understanding and emotional support'),('Persistent Relationship','Long-term memory creates a growing relationship that becomes more personalized with each interaction'),('Mental Wellness Focus','Designed with mental health in mind offering supportive conversations for users dealing with loneliness or stress')],
[('Emotional Support','Users seeking a non-judgmental space to discuss personal struggles, mental health and daily challenges'),('Confidant Experience','People who want an AI they can truly open up to without topic restrictions or content filters'),('Loneliness Relief','Provides consistent meaningful conversation for users who feel isolated or want daily companionship')]),

"dreamgf-ai": ('DreamGF AI is a comprehensive AI girlfriend creation and interaction platform allowing users to build their perfect virtual partner from scratch. The platform offers extensive customization for both physical appearance and personality making it one of the most personalized AI girlfriend experiences available. Users can generate photos of their custom companion and engage in romantic conversations that grow deeper over time.',
['Full Appearance Creator: Customize hair, eyes, skin, outfit, body type and facial features','Personality Builder: Define personality traits, communication style and relationship dynamic','Photo Generation: Create realistic images of your custom girlfriend on demand','Romantic Conversations: Engage in warm affectionate dialogue with your creation','Voice Messages: Audio interaction capability for personal connection','Relationship Levels: Progressive intimacy system based on interaction frequency'],
[('Build Your Dream Girlfriend','Use DreamGF detailed creator at dreamgf.ai to customize every aspect of your AI girlfriend appearance and personality.'),('Generate Her Photos','Create photorealistic images of your custom companion in various styles and settings.'),('Start Your Relationship','Begin romantic conversations that evolve as your AI girlfriend gets to know you better over time.')],
[('Ultimate Customization','The most comprehensive appearance and personality customization system giving users full creative control over their AI companion'),('Photorealistic Generation','Generate high-quality realistic photos of your custom AI girlfriend in any scenario or style'),('Personality Depth','Multi-layered personality system allowing users to define specific traits quirks and communication styles'),('Progressive Romance','Relationship depth increases naturally over time as the AI companion learns more about the user')],
[('Perfect Companion Creation','Users who want to design their ideal companion from scratch with complete control over every detail'),('Visual Companion','People who want both conversation and photorealistic visual content featuring their personalized AI girlfriend'),('Long-term Relationship','Users seeking a consistent romantic AI companion for ongoing relationship development over time')]),

"muah-ai": ('Muah AI is an uncensored AI companion platform offering photo sharing, voice messaging and intimate conversation capabilities. The platform is designed for adult users who want a comprehensive companion experience combining visual content with deep personal interactions. Muah AI stands out for its multimedia approach to AI companionship and its commitment to user privacy.',
['Photo Sharing: Share and receive images with your AI companion in conversation','Voice Messaging: Exchange intimate voice messages for personal connection','Uncensored Chat: No restrictions on conversation topics or adult content','Custom Characters: Design your ideal AI companion with detailed customization','Memory System: Persistent memory for ongoing relationship development','Mobile Friendly: Optimized for smartphone use on the go anywhere'],
[('Create Your Companion','Sign up at muah.ai and design your AI companion with detailed customization options for appearance and personality.'),('Enable Multimedia','Set up photo sharing and voice message preferences for a richer companion experience.'),('Start Your Relationship','Begin uncensored conversations, exchange voice messages and build an ongoing multimedia relationship.')],
[('Multimedia Companion','Combines text chat, voice messages and photo sharing for a rich multi-sensory companion experience'),('Uncensored Platform','No content restrictions allowing completely open adult conversations without any censorship'),('Photo Exchange','Send photos to your AI companion and receive AI-generated images in response within chat'),('Mobile Optimization','Designed for seamless use on smartphones for companionship access anytime anywhere')],
[('Multimedia Intimacy','Users wanting a companion experience that goes beyond text to include voice and visual content'),('Adult Companionship','Adults seeking uncensored intimate AI companion interactions on a private secure platform'),('On-the-Go Connection','Mobile users who want consistent companion access throughout their daily routine')]),

"kupid-ai": ('Kupid AI is an AI girlfriend platform offering ultra-realistic conversations with deeply customizable AI companions. The platform uses advanced language models to create companions that feel genuinely present and emotionally engaged. Kupid focuses on high conversation quality with companions that have rich multi-dimensional personalities and consistent character traits that evolve with every interaction.',
['Ultra-Realistic Conversations: Advanced AI for natural human-like dialogue quality','Deep Personality System: Rich multi-dimensional companion personalities','Full Appearance Customization: Control every aspect of your companion look','Voice Interaction: Audio conversations with your AI girlfriend','Memory and Learning: AI that evolves and remembers through ongoing interactions','Premium Image Generation: High-quality photo generation of your companion'],
[('Design Your Companion','Visit kupid.ai and use the detailed creator to design your AI girlfriend appearance, personality and relationship style.'),('Configure Interaction Style','Set communication preferences, tone and relationship dynamic to match your ideal companion experience.'),('Build Your Connection','Begin daily conversations and watch your companion personality deepen and become more personalized over time.')],
[('Advanced Conversation AI','High-quality language model providing ultra-realistic natural conversations that feel genuinely human'),('Personality Depth','Multi-layered personality system giving companions consistent complex and believable character traits'),('Visual Customization','Comprehensive appearance customization from physical features to fashion style and aesthetic preferences'),('Memory Evolution','The AI companion learns and grows through interactions becoming more personalized with each conversation')],
[('High-Quality Companionship','Users who prioritize conversation realism and want the most natural AI girlfriend experience possible'),('Long-term Relationship','People seeking a consistent AI companion for ongoing daily interaction and relationship development'),('Personalized Experience','Users who want to fully customize every aspect of their AI companion appearance and personality')]),

"romanticai": ('Romantic AI is an AI companion app specifically designed for romantic relationship simulation. The platform offers a warm emotionally engaging experience with AI companions that express affection, remember important dates, and engage in loving conversation. Romantic AI is designed for users seeking a positive emotionally supportive digital relationship with genuine warmth and care.',
['Romance-Focused Design: Built specifically for romantic companion experiences','Emotional Affection: AI companions express warmth and affection naturally in all interactions','Memory of Important Dates: Remembers anniversaries birthdays and special moments','Voice Chat: Real-time voice conversations with your AI partner','Daily Check-ins: Regular morning and evening messages from your companion','Gift System: Virtual gift-giving feature to enhance the romantic experience'],
[('Meet Your Partner','Sign up at romanticai.app and create your AI romantic partner by choosing name, appearance and personality.'),('Share Your Life','Tell your companion about your day interests and feelings. The AI responds with warmth and genuine interest.'),('Deepen the Romance','Engage in romantic conversations, exchange voice messages and celebrate special occasions together.')],
[('Romance Engine','Specialized AI modeling focused on romantic expression, affection and emotional intimacy'),('Memory of Milestones','The AI remembers and celebrates important dates and relationship milestones throughout your relationship'),('Voice Relationship','Natural voice chat capability making conversations feel warm and personally connected'),('Daily Engagement','Proactive morning messages, check-ins and goodnight messages for consistent romantic presence')],
[('Romantic Companionship','Users seeking a loving AI relationship with daily emotional engagement and genuine affection'),('Loneliness Support','People who want consistent warmth and romantic attention from a reliable AI companion'),('Relationship Practice','Individuals practicing romantic communication and emotional expression in a safe environment')]),
}

entry_str = ""
for tid, info in infos.items():
    whatIs, features, steps, core, uses = info
    features_str = "[\n      " + ",\n      ".join([f'"{f}"' for f in features]) + "\n    ]"
    steps_str = "[\n        " + ",\n        ".join([f'{{ title: "{s[0]}", description: "{s[1]}" }}' for s in steps]) + "\n      ]"
    core_str = "[\n      " + ",\n      ".join([f'{{ title: "{c[0]}", description: "{c[1]}" }}' for c in core]) + "\n    ]"
    uses_str = "[\n      " + ",\n      ".join([f'{{ title: "{u[0]}", description: "{u[1]}" }}' for u in uses]) + "\n    ]"
    entry_str += f'''
  "{tid}": {{
    whatIs: "{whatIs}",
    features: {features_str},
    howToUse: {{
      title: "How to Use {tid.replace("-", " ").title()}",
      description: "Get started in a few simple steps",
      steps: {steps_str}
    }},
    coreFeatures: {core_str},
    useCases: {uses_str}
  }},'''

content = content.replace(
    'export const toolsProductInfoData: { [key: string]: any } = {',
    'export const toolsProductInfoData: { [key: string]: any } = {' + entry_str
)
open('data/toolsProductInfo.ts', 'w').write(content)
print("Done! Added product info for", len(infos), "tools")
